title: 土
description: >
  **I am Rex.**_*A professional in chilling with myself*_as well as_*A numb analyst with styles*
copyright: trexwithoutt
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: 
facebook_username: "rex.zhou.50"
linkedin_username: "rex-zhou-4bb38a148"
instagram_username: "trexwithoutt"
pinterest_username: "rex0138"
github_username:  "trexwithoutt"
feed_icon: "https://github.com/trexwithoutt/trexwithoutt.github.io/blob/master/images/Rex-Zhou-Resume.pdf"
email: "rexzhe1230@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
