title: Strata by HTML5 UP
description: >
  **I am Rex, a professional in chilling with myself**.
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "#"
linkedin_username: "#"
instagram_username: "trexwithoutt"
pinterest_username:
flickr_username:
github_username:  "#"
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
